import:
- logstash-plugins/.ci:travis/travis.yml@1.x

addons:
  apt:
    sources:
      - sourceline: 'ppa:chris-lea/redis-server'
    packages:
      - redis-server

before_install:
  - sudo service redis-server stop
  - sudo service redis-server start --bind 0.0.0.0
